CREATE DATABASE IF NOT EXISTS oai_db;
CREATE USER IF NOT EXISTS 'test'@'127.0.0.1' IDENTIFIED BY 'test';
CREATE USER IF NOT EXISTS 'test'@'localhost' IDENTIFIED BY 'test';
GRANT ALL PRIVILEGES ON oai_db.* TO 'test'@'127.0.0.1';
GRANT ALL PRIVILEGES ON oai_db.* TO 'test'@'localhost';
FLUSH PRIVILEGES;
